# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_upvotecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvoteCount',
            field=models.IntegerField(),
        ),
    ]
