# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171106_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
