# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171108_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
